# Put document versions here for every major or minor release
# Every TOML list item contains the following properties:
# - "version"   - text that appears in versions menu
# - "dirpath"   - directory name (relative to contentDir) where documentation
#                 for given version resides
# - "url"       - url for link in version menu. May be absolute URL.
# - "latestTag" - docker image tag for the latest patch version. Must be changed
#                 on every patch release of respective branch
[[versions]]
version = "dev"
dirpath = "dev"
url = "/dev/"
[[versions]]
version = "1.12"
dirpath = "latest"
url = "/latest/"
[[versions]]
version = "1.11"
dirpath = "1.11"
url = "/1.11/"
[[versions]]
version = "1.10"
dirpath = "1.10"
url = "/1.10/"
[[versions]]
version = "1.9"
dirpath = "1.9"
url = "/1.9/"
[[versions]]
version = "1.8"
dirpath = "1.8"
url = "/1.8/"
[[versions]]
version = "1.7"
dirpath = "1.7"
url = "/1.7/"
[[versions]]
version = "1.6"
dirpath = "1.6"
url = "/1.6/"
[[versions]]
version = "1.5"
dirpath = "1.5"
url = "/1.5/"
