# Put document versions here for every major or minor release
# Every TOML list item contains the following properties:
# - "version"   - text that appears in versions menu
# - "dirpath"   - directory name (relative to contentDir) where documentation
#                 for given version resides
# - "url"       - url for link in version menu. May be absolute URL.
# - "latestTag" - docker image tag for the latest patch version. Must be changed
#                 on every patch release of respective branch
#[[versions]]
#    version = "Latest - 1.3"
#    dirpath = "1.3"
#    url = "/1.3/"
[[versions]]
    version = "1.2"
    dirpath = "1.2"
    url = "/1.2/"
[[versions]]
    version = "1.1"
    url = "https://gooddata-sdk.readthedocs.io/en/v1.1.0/"
