# Put document versions here for every major or minor release
# Every TOML list item contains the following properties:
# - "version"   - text that appears in versions menu
# - "dirpath"   - directory name (relative to contentDir) where documentation
#                 for given version resides
# - "url"       - url for link in version menu. May be absolute URL.
# - "latestTag" - docker image tag for the latest patch version. Must be changed
#                 on every patch release of respective branch
[[versions]]
version = "dev"
dirpath = "dev"
url = "/dev/"
sitemapExclude = true
[[versions]]
version = "1.55"
dirpath = "latest"
url = "/latest/"
[[versions]]
version = "1.54"
dirpath = "1.54"
url = "/1.54/"
[[versions]]
version = "1.53"
dirpath = "1.53"
url = "/1.53/"
[[versions]]
version = "1.52"
dirpath = "1.52"
url = "/1.52/"
