# Put document versions here for every major or minor release
# Every TOML list item contains the following properties:
# - "version"   - text that appears in versions menu
# - "dirpath"   - directory name (relative to contentDir) where documentation
#                 for given version resides
# - "url"       - url for link in version menu. May be absolute URL.
# - "latestTag" - docker image tag for the latest patch version. Must be changed
#                 on every patch release of respective branch
[[versions]]
version = "dev"
dirpath = "dev"
url = "/dev/"
sitemapExclude = true
[[versions]]
version = "1.59"
dirpath = "latest"
url = "/latest/"
[[versions]]
version = "1.58"
dirpath = "1.58"
url = "/1.58/"
[[versions]]
version = "1.57"
dirpath = "1.57"
url = "/1.57/"
[[versions]]
version = "1.56"
dirpath = "1.56"
url = "/1.56/"
