# (C) 2025 GoodData Corporation
[project]
name = "gooddata-pipelines"
version = "1.60.0"
description = "GoodData Cloud lifecycle automation pipelines"
authors = [{ name = "GoodData", email = "support@gooddata.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic (>=2.9.2,<3.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "types-requests (>1.0.0,<3.0.0)",
    "gooddata-sdk~=1.60.0",
    "boto3 (>=1.39.3,<2.0.0)",
    "boto3-stubs (>=1.39.3,<2.0.0)",
    "azure-storage-blob (>=12.19.0,<13.0.0)",
    "azure-identity (>=1.15.0,<2.0.0)",
    "types-pyyaml (>=6.0.12.20250326,<7.0.0)",
]

[tool.ruff]
exclude = [".venv"]
line-length = 80

[dependency-groups]
test = [
    "pytest (>=8.3.5,<9.0.0)",
    "pytest-cov~=6.0.0",
    "pytest-json-report==1.5.0",
    "pytest-mock (>=3.14.0,<4.0.0)",
    "moto (>=5.1.6,<6.0.0)",
    "orjson (>=3.11.3,<4.0.0)",
]

[tool.ty.analysis]
allowed-unresolved-imports = ["boto3.**", "botocore.**", "mypy_boto3_s3.**", "azure.**"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
