# (C) 2021 GoodData Corporation
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# ignore all generated code + all snapshots; snapshots must not be processed otherwise they stop matching due to
# addition of new lines
exclude: (gooddata-afm-client|gooddata-metadata-client|gooddata-scan-client|gooddata-api-client|.*\.snapshot\..*|.openapi-generator/custom_templates)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [ '--maxkb=600' ]
      - id: check-case-conflict
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.220
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args: [ "--force-exclude" ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: copyright
        name: Copyright
        description: Scan for missing copyright
        entry: scripts/check_copyright.py
        args: [ "--update", "FILES" ]
        language: script
        types: [ text ]
