# (C) 2025 GoodData Corporation
[project]
name = "gooddata-fdw"
version = "1.58.0"
description = "GoodData Cloud Foreign Data Wrapper For PostgreSQL"
readme = "README.md"
license = "MIT"
authors = [
    {name = "GoodData", email = "support@gooddata.com"}
]
keywords = [
    "gooddata",
    "fdw",
    "postgresql",
    "analytics",
    "headless",
    "business",
    "intelligence",
    "headless-bi",
    "cloud",
    "native",
    "semantic",
    "layer",
    "sql",
    "metrics",
]
requires-python = ">=3.10"
dependencies = [
    "gooddata-sdk~=1.58.0",
    # "multicorn>=1.4.0",  # Uncommented as it was in original setup.py
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Database",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Typing :: Typed",
]

[project.urls]
Documentation = "https://gooddata-fdw.readthedocs.io/en/v1.58.0"
Source = "https://github.com/gooddata/gooddata-python-sdk"

[dependency-groups]
test = [
    "pytest~=8.3.4",
    "pytest-cov~=6.0.0",
    "vcrpy~=8.0.0",
    # TODO - Bump the version together with bumping the version of openapi generator
    "urllib3~=2.6.0",
    "pyyaml",
    "tests_support",
]
type = [
    "mypy~=1.11.2",
    "pydantic~=2.12.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/gooddata_fdw"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
