name: Dev release from master

on:
  workflow_dispatch:
    inputs:
      BRANCH_NAME:
        type: string
        description: 'Branch name to release from'
        default: "master"

jobs:
  dev-release:
    name: Releasing master as dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - gooddata-api-client
          - gooddata-pandas
          - gooddata-fdw
          - gooddata-sdk
          - gooddata-dbt
          - gooddata-flight-server
          - gooddata-flexconnect
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.BRANCH_NAME }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Install pip & tbump
        run: python -m pip install --upgrade pip tbump
      - name: Bump to dev
        run: tbump  --only-patch --non-interactive $(./scripts/next_dev.sh)
      - name: Install dependencies
        run: pip install build
      - name: Build ${{ matrix.component }}
        run: |
          cd ${{ matrix.component }}
          python -m build
      - name: Push ${{ matrix.component}} to pypi
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ${{ matrix.component }}/dist
          verbose: true
