name: tests
on:
  workflow_call:
    inputs:
      changed-python-modules:
        type: string
        default: 'false'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: ${{inputs.changed-python-modules == 'true'}}
    strategy:
      matrix:
        python_version: [py314, py313, py312, py311, py310]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execute tests
        run: |
          make test-ci
        env:
          TEST_ENVS: ${{ matrix.python_version }}
      - name: Upload coverage to Codecov
        if: ${{ matrix.python_version == 'py314' }}
        uses: codecov/codecov-action@v5
        with:
          files: ./packages/gooddata-sdk/coverage.xml,./packages/gooddata-pandas/coverage.xml,./packages/gooddata-fdw/coverage.xml,./packages/gooddata-flight-server/coverage.xml,./packages/gooddata-flexconnect/coverage.xml,./packages/gooddata-dbt/coverage.xml,./packages/gooddata-pipelines/coverage.xml
  lint-and-format-check:
    runs-on: ubuntu-latest
    if: ${{inputs.changed-python-modules == 'true'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python 3.14
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.14
      - name: Install dependencies
        run: |
          uv sync --only-group lint --locked
      - name: pep8 and formatting check
        run: |
          make format
  types-check:
    runs-on: ubuntu-latest
    if: ${{inputs.changed-python-modules == 'true'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python 3.14
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: |
          uv sync --group type --locked
      - name: type check
        run: |
          make type-check
