name: tests
on:
  pull_request:
    branches:
      - master
    paths:
      - '.docker/**'
      - 'gooddata-fdw/**'
      - '!gooddata-fdw/docs/**'
      - 'gooddata-pandas/**'
      - '!gooddata-pandas/docs/**'
      - 'gooddata-sdk/**'
      - '!gooddata-sdk/docs/**'
      - '*.mk'
      - 'Makefile'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [py39, py38, py37]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests
        run: |
          make test-ci
        env:
          TEST_ENVS: ${{ matrix.python_version }}
      - name: Upload coverage to Codecov
        if: ${{ matrix.python_version == 'py39' }}
        uses: codecov/codecov-action@v2
        with:
          files: ./gooddata-sdk/coverage.xml,./gooddata-pandas/coverage.xml,./gooddata-fdw/coverage.xml
          fail_ci_if_error: true
  lint-and-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: |
            lint-requirements.txt
            fmt-requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lint-requirements.txt -r fmt-requirements.txt
      - name: Pep8 check
        run: |
          make lint
      - name: Formatting check
        run: |
          make format
  types-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: |
            tox-requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tox-requirements.txt
      - name: mypy check
        run: |
          make mypy
